title: Snowbotics Documentation 
description: Documentation for FLL team 39131 Snowbotics code
theme: just-the-docs

url: https://snowbotics39131.github.io/SnowboticsDocumentation

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/snowbotics39131/SnowboticsDocumentation